name: testytest
on:
  push:
    branches: [ "main" ]
    # paths: ['**/mgmt/**/*.hcl']

  workflow_dispatch:

jobs:
  tf-plan:
    runs-on: codebuild-hamda-5ra-${{ github.run_id }}-${{ github.run_attempt }}
    environment: approval
    permissions: write-all
    steps:
      - name: Checks
        uses: actions/checkout@v4

      - name: Debug
        run: |
          echo Hi
